# Planner Constants
BALL_NOT_VISIBLE = 'ball_unreachable'
BALL_OUR_ZONE = 'ball_our_zone'
BALL_OUR_ZONE_AT_WALL = 'ball_our_zone_at_wall'
POSSESSION = 'possession'
BALL_NOT_IN_OUR_ZONE = 'ball_not_in_our_zone'
FOLLOWING_BALL = 'following ball'
BALL_OUR_DEFENDER_ZONE = 'ball_their_defender_zone'
BALL_THEIR_ATTACKER_ZONE = 'ball_their_attacker_zone'
BALL_THEIR_DEFENDER_ZONE = 'ball_their_defender_zone'

# Strategy State Constants
INIT = 'init'
IDLE = 'idle'
GRABBER_CLOSED = 'grabber_closed'
MOVING_TO_BALL = 'moving_to_ball'
KICKING = 'kicking'
GRABBING_BALL = 'grabbing_ball'
FACING_GOAL = 'facing_goal'
BALL_IN_GRABBER_AREA = 'ball_in_grabber_area'
TURNING_TO_DEFENDER = 'turning_to_def'
TURNING_TO_BALL = 'turning_to_ball'
TURNING_TO_GOAL = 'turning_to_goal'
FACING_BALL = 'facing_ball'
OPENING_GRABBER = 'opening_grabber'
CLOSING_GRABBER = 'closing_grabber'
TURNING_TO_DEST = 'turning_to_dest'
MOVING_TO_DEST = 'moving_to_dest'
DONE = 'done'

FINDING_PATH = 'finding path'
