# Planner Constants
BALL_NOT_VISIBLE = 'ball_unreachable'
GETTING_BALL = 'ball_our_zone'
POSSESSION = 'possession'
BALL_NOT_IN_OUR_ZONE = 'ball_not_in_our_zone'
AWAITING_PASS = 'awaiting_pass'
DEFENDING = 'defending'
INTERCEPT = 'intercept'

# Strategy State Constants
INIT = 'init'
IDLE = 'idle'
GRABBER_CLOSED = 'grabber_closed'
MOVING_TO_BALL = 'moving_to_ball'
KICKING = 'kicking'
GRABBING_BALL = 'grabbing_ball'
FACING_GOAL = 'facing_goal'
BALL_IN_GRABBER_AREA = 'ball_in_grabber_area'
TURNING_TO_DEFENDER = 'turning_to_def'
TURNING_TO_BALL = 'turning_to_ball'
TURNING_TO_GOAL = 'turning_to_goal'
FACING_BALL = 'facing_ball'
OPENING_GRABBER = 'opening_grabber'
CLOSING_GRABBER = 'closing_grabber'
TURNING_TO_DEST = 'turning_to_dest'
MOVING_TO_DEST = 'moving_to_dest'
DONE = 'done'
GOTO_SHOOT_SPOT = 'go_to_shoot_spot'
CHOOSING_SHOT_ANGLE = 'choosing_spot'
FOLLOWING_BALL = 'following_ball'
GETTING_SQUARE = 'getting square'
TRACKING_BALL = 'tracking ball'
FINDING_PATH = 'finding path'
FIXATE = 'fixate'
TURNING_TO_WALL = 'turning to wall'
TRACKING_SHOT_PATH = 'tracking shot path'
